### ISSUE TITLE
Don't download IDEA in sbt build file

### ISSUE THREAD

**Issue by nixel2007** [intellij-lsp/intellij-lsp-plugin#3]
It is already downloaded in gradle task.

Maybe we should remove SBT itself?

**Comment by NipunaRanasinghe** [comment]
IMO it would be better if we can continue with Gradle instead of SBT since SBT suffers from major incompatible changes between versions.

**Comment by nixel2007** [comment]
I have no exp in SBT itself, but i've already use gradle for building other idea plugin. So... if gradle can compile scala (and it can), i can't find a reason to support SBT also.
